### ISSUE TITLE
therubyracer gem install fails on Ubuntu, ruby 1.8.7

### ISSUE THREAD

**Issue by milosgajdos83** [cowboyd/therubyracer#191]
When trying to install the gem I'm getting the following error:

Could not create Makefile due to some reason, probably lack of
necessary libraries and/or headers.  Check the mkmf.log file for more
details.  You may need configuration options.

Provided configuration options:
	--with-opt-dir
	--without-opt-dir
	--with-opt-include
	--without-opt-include=${opt-dir}/include
	--with-opt-lib
	--without-opt-lib=${opt-dir}/lib
	--with-make-prog
	--without-make-prog
	--srcdir=.
	--curdir
	--ruby=/usr/bin/ruby1.8
extconf.rb:16: undefined method `include_path' for Libv8:Module (NoMethodError)

Gem files will remain installed in /var/lib/gems/1.8/gems/therubyracer-0.10.2 for inspection.
Results logged to /var/lib/gems/1.8/gems/therubyracer-0.10.2/ext/v8/gem_make.out

I tried all sort of hacks but none has worked. Any ideas ?

**Comment by cowboyd** [comment]
Closing this, since we're now on `3.16.14.10`
