### ISSUE TITLE
Undefined Symbol when using --with-system-v8

### ISSUE THREAD

**Issue by clark800** [cowboyd/therubyracer#254]
I'm trying to install Gitlab on an ARM5 system running Arch Linux ARM. The libv8 gem build fails with the default settings, so I built V8 version 3.11.8 from source and copied it to the system location at /usr/lib/libv8.so. I also copied the executable to /usr/bin/d8, and the headers to /usr/include. Then I built libv8 using
```
gem install libv8 -v '3.11.8.17' --user-install -- --with-system-v8
```
and manually copied it into the bundle (the bundle install of the libv8 gem fails with a "NoMethodError: undefined method `size' for nil:NilClass" even with the "bundle config build.libv8 --with-system-v8" option). Then the bundle install succeeded. But when I try to do a bundle exec, therubyracer fails due to a missing symbol. The symbol is in the system's libv8.so, so it seems that libv8.so is not being loaded. Here is an excerpt from my console.

```
Using libv8 (3.11.8.17)
...
Installing therubyracer (0.11.4) 
Installing uglifier (1.3.0) 
Your bundle is complete!
Gems in the groups development, test and mysql were not installed.
It was installed into ./vendor/bundle
$ bundle exec rake db:setup RAILS_ENV=production
ruby: symbol lookup error: /home/git/gitlab/vendor/bundle/ruby/2.0.0/gems/therubyracer-0.11.4/lib/v8/init.so: undefined symbol: _ZN2v82V821AddGCPrologueCallbackEPFvNS_6GCTypeENS_15GCCallbackFlagsEES1_
$ nm /usr/lib/libv8.so | grep AddGCPrologue
000404e4 T _ZN2v82V821AddGCPrologueCallbackEPFvNS_6GCTypeENS_15GCCallbackFlagsEES1_
```
And from "gem env":
```
  - RUBYGEMS VERSION: 2.0.3
  - RUBY VERSION: 2.0.0 (2013-02-24 patchlevel 0) [armv5tel-linux-eabi]
```
The bundler version is 1.3.5.

**Comment by cowboyd** [comment]
This should have been resolved with `3.14.16.x`
