### ISSUE TITLE
unable to build therubyracer/libv8 on arm A10

### ISSUE THREAD

**Issue by Lyann** [cowboyd/therubyracer#255]
Hello,

currently having the problem to be unable to build therubyracer, because libv8 linking error. I tried to hack the compiler switch -fPIC into libv8/therubyracer, but without any success. Also there are a bit too much makefiles scons/rakefile/gby therefore not so easy to find the correct position where to add. Would be nice if someone could help me, I wasted already too much time into it. Setting up a qemu with an A10 vexpress image would be next step, but requires some time. Cannot use the system libv8 because it's very old, using currently the linaro quanta image on a cubieboard.

Thanks in advance

Copy & paste of the error at building: 
Installing therubyracer (0.11.4)
Gem::Installer::ExtensionBuildError: ERROR: Failed to build gem native extension.

        /usr/bin/ruby1.9.1 extconf.rb
checking for main() in -lpthread... yes
creating Makefile

...

linking shared-object v8/init.so
/usr/bin/ld: /home/git/gitlab/vendor/bundle/ruby/1.9.1/gems/libv8-3.11.8.17/vendor/v8/out/arm.release/obj.target/tools/gyp/libv8_snapshot.a(libraries.o): relocation R_ARM_THM_MOVW_ABS_NC against `a local symbol' can not be used when making a shared object; recompile with -fPIC
/home/git/gitlab/vendor/bundle/ruby/1.9.1/gems/libv8-3.11.8.17/vendor/v8/out/arm.release/obj.target/tools/gyp/libv8_snapshot.a: could not read symbols: Bad value
collect2: error: ld returned 1 exit status
make: *** [init.so] Error 1

Gem files will remain installed in /home/git/gitlab/vendor/bundle/ruby/1.9.1/gems/therubyracer-0.11.4 for inspection.
Results logged to /home/git/gitlab/vendor/bundle/ruby/1.9.1/gems/therubyracer-0.11.4/ext/v8/gem_make.out
An error occurred while installing therubyracer (0.11.4), and Bundler cannot continue.
Make sure that `gem install therubyracer -v '0.11.4'` succeeds before bundling.

**Comment by Karengc** [comment]
There's an official Omnibus package for the RPi2, see 'Omnibus package for Raspberry Pi 2' on https://about.gitlab.com/installation/

**Comment by cowboyd** [comment]
resolved with #132
