### ISSUE TITLE
compilation on arm fails

### ISSUE THREAD

**Issue by FransM** [cowboyd/therubyracer#266]
I tried to compile therubyracer on armv7 (fedora 19) using git head and after installing libv8 from git head using 
    git clone git://github.com/cowboyd/libv8.git
    cd libv8
    bundle install
    bundle exec rake checkout
    bundle exec rake compile
After that in therubyracer I did a bundle install, got an error message about thor not being found, added thor to the Gemfile (is this an error?) then reran bundle install, then tried rake compile but it fails on the very first file.

Anyone an idea what is wrong or how to fix this. (note that I need to use my own v8 as the version in rubygems does not support arm yet)

Thansk in advance! Frans

[frans@localhost therubyracer]$ rake compile
cd tmp/armv7hl-linux/init/2.0.0
gmake
g++ -I. -I/usr/include -I/usr/include/ruby/backward -I/usr/include -I../../../../ext/v8 -D_FILE_OFFSET_BITS=64  -Wall -g -rdynamic -fPIC -O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector --param=ssp-buffer-size=4 -grecord-gcc-switches  -march=armv7-a -mfpu=vfpv3-d16  -mfloat-abi=hard  -o context.o -c ../../../../ext/v8/context.cc
In file included from ../../../../ext/v8/context.cc:1:0:
../../../../ext/v8/context.cc: In static member function ‘static VALUE rr::Context::SetEmbedderData(VALUE, VALUE, VALUE)’:
../../../../ext/v8/context.cc:81:23: error: ‘class v8::Context’ has no member named ‘SetEmbedderData’
   Void(Context(self)->SetEmbedderData(NUM2INT(index), Value(data)));
                       ^
../../../../ext/v8/rr.h:33:20: note: in definition of macro ‘Void’
 #define Void(expr) expr; return Qnil;
                    ^
../../../../ext/v8/context.cc: In static member function ‘static VALUE rr::Context::GetEmbedderData(VALUE, VALUE)’:
../../../../ext/v8/context.cc:85:23: error: ‘class v8::Context’ has no member named ‘GetEmbedderData’
   Void(Context(self)->GetEmbedderData(NUM2INT(index)));
                       ^
../../../../ext/v8/rr.h:33:20: note: in definition of macro ‘Void’
 #define Void(expr) expr; return Qnil;
                    ^
gmake: *** [context.o] Error 1
rake aborted!
Command failed with status (2): [gmake...]
/home/frans/.gem/ruby/gems/rake-compiler-0.8.3/lib/rake/extensiontask.rb:112:in `block (2 levels) in define_compile_tasks'
/home/frans/.gem/ruby/gems/rake-compiler-0.8.3/lib/rake/extensiontask.rb:111:in `block in define_compile_tasks'
Tasks: TOP => compile => compile:armv7hl-linux => compile:init:armv7hl-linux => copy:init:armv7hl-linux:2.0.0 => tmp/armv7hl-linux/init/2.0.0/init.so
(See full trace by running task with --trace)
[frans@localhost therubyracer]$

**Comment by cowboyd** [comment]
Should be resolved with libv8 >= `3.16.14`
