### ISSUE TITLE
therubyracer on Fedora

### ISSUE THREAD

**Issue by voxik** [cowboyd/therubyracer#278]
As you probably noticed, we package therubyracer gem for Fedora for some while already. We would like to update to the most recent version, but the split of libv8 from therubyracer gem makes the things even harder the previously. Let me explain.

Previously, therubyracer bundled some version of v8. We either build against this version or the system version of v8. That was more or less OK.

However, currently, the separated libv8 is at 3.16.14.3 version. If we use the `--with-system-v8` switch, it says to therubyracer that it should build against system version, which is currently 3.14.5.10. So the first issue is that libv8 will not correspond with the version of v8 which is actually in use.

Moreover, therubyracer enforces libv8 ~> 3.16.14.0 This in turn means, that every update of libv8 on your side means that we should update as well, although the libv8 in background is not changing.

I must say that all these places us into unfortunate situation of mixture of versions. Do you have any proposal how to get out of this situation? Thanks for your help.

**Comment by ignisf** [comment]
OpenSUSE are packaging libv8 in source form, see http://rpm.pbone.net/index.php3/stat/4/idpl/23779508/dir/opensuse_12.x/com/rubygem-libv8-3.16.14.1-2.2.x86_64.rpm.html
