### ISSUE TITLE
Latest Failed install on Ubuntu 10.04LTS

### ISSUE THREAD

**Issue by sr3d** [cowboyd/therubyracer#284]
I tried installing Ruby 1.9.3 and Rails on my 3-year old VPS running Ubuntu 10.04LTS, and I'm using the twitter-bootstrap gem that depends on TheRubyRacer but I wasn't able to install the latest rubyracer.  The system is x86_64. 

root@ramon:~/temp/test# uname -a
Linux ramon 3.9.3-x86_64-linode33 #1 SMP Mon May 20 10:22:57 EDT 2013 x86_64 GNU/Linux

However, if I install the 0.11.0beta8 version then the gem would be installed successfuly.  

Failed installation:

root@ramon:~/temp/test# gem install therubyracer
Fetching: libv8-3.16.14.3-x86_64-linux.gem (100%)
Successfully installed libv8-3.16.14.3-x86_64-linux
Building native extensions.  This could take a while...
ERROR:  Error installing therubyracer:
  ERROR: Failed to build gem native extension.

    /usr/local/bin/ruby extconf.rb
checking for main() in -lpthread... yes
creating Makefile

make
compiling constraints.cc
compiling array.cc
compiling value.cc
compiling invocation.cc
compiling primitive.cc
compiling trycatch.cc
compiling context.cc
compiling exception.cc
compiling template.cc
compiling accessor.cc
compiling object.cc
compiling script.cc
compiling external.cc
compiling stack.cc
compiling gc.cc
compiling backref.cc
compiling heap.cc
compiling v8.cc
compiling constants.cc
compiling date.cc
compiling function.cc
compiling rr.cc
compiling message.cc
compiling init.cc
compiling string.cc
compiling handles.cc
compiling signature.cc
compiling locker.cc
linking shared-object v8/init.so
g++: /usr/local/lib/ruby/gems/1.9.1/gems/libv8-3.16.14.3-x86_64-linux/vendor/v8/out/ia32.release/obj.target/tools/gyp/libv8_base.a: No such file or directory
g++: /usr/local/lib/ruby/gems/1.9.1/gems/libv8-3.16.14.3-x86_64-linux/vendor/v8/out/ia32.release/obj.target/tools/gyp/libv8_snapshot.a: No such file or directory
make: *** [init.so] Error 1

Gem files will remain installed in /usr/local/lib/ruby/gems/1.9.1/gems/therubyracer-0.12.0 for inspection.
Results logged to /usr/local/lib/ruby/gems/1.9.1/gems/therubyracer-0.12.0/ext/v8/gem_make.out

root@ramon:~/temp/test# gem install therubyracer -v 0.11.0beta8 --pre
Fetching: therubyracer-0.11.0beta8-x86_64-linux.gem (100%)
Successfully installed therubyracer-0.11.0beta8-x86_64-linux
Installing ri documentation for therubyracer-0.11.0beta8-x86_64-linux
1 gem installed

I'm not sure if this is related or not:  https://github.com/cowboyd/libv8/issues/109 

And https://github.com/cowboyd/therubyracer/issues/262 

I also trying to install older version of the rubyracer but it'd look into the ia32 target instead of the x64 (should be libv8-3.16.14.3-x86_64-linux/vendor/v8/out/x64.release instead of libv8-3.16.14.3-x86_64-linux/vendor/v8/out/ia32.release).

Because the 0.11.0beta8 works but the later one failed, I suspect it would be something up with the compilation script.

**Comment by jfharden** [comment]
I'm having the same problem on Debian 7.8 (also in  Linode I might add). I really want to avoid using my system ruby since that is 1.9.3 and I'd like to use a 2.x variant.

**Comment by mrdziuban** [comment]
Also on 32-bit Ubuntu with a 64-bit kernel. I solved this in a really hacky way:

```bash
# install 64-bit libv8
gem install libv8
# install 32-bit libv8
gem install libv8 --platform x86
# copy missing 32-bit files to 64-bit gem directory (replace paths as necessary)
cp -R /usr/local/rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/libv8-3.16.14.11-x86-linux/vendor/v8/out/ia32.release /usr/local/rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/libv8-3.16.14.11-x86_64-linux/vendor/v8/out/
# install therubyracer
gem install therubyracer
```

While this works, I'm not too happy with the solution. There's no way to specify that this needs to be done in my `Gemfile` and if I want to upgrade `libv8` in the future, I'll need to do it all again.

**Comment by mrdziuban** [comment]
As an update to my previous comment, I found a better way around this issue. Using RVM (instead of rbenv), I forced the 32-bit version of Ruby to be installed:
```
rvm install 2.2.2 --32
```
After doing that, the 32-bit version of libv8 was installed by default and therubyracer installed without any problems.
