### ISSUE TITLE
Usage of `old-style callbacks' causes compilation failures against v8 3.27

### ISSUE THREAD

**Issue by ignisf** [cowboyd/therubyracer#302]
Relevant changelog entry: https://github.com/v8/v8/blob/3e283f444dfd2ffd4550f7c726888f427ec0a0ab/ChangeLog#L2033

**Comment by cowboyd** [comment]
I think it's clear at this point that we're going to need to move forward with whatever version of libv8 helps us provide the best development experience with TRR. 

`--with-system-v8` is for those who wish to be responsible for compiling their own library from source, not those who wish to use whatever version of v8 happens to ship with their distro. 

It's unreasonable for us to lock ourselves into a v8 API version when V8 is evolving so quickly.
