### ISSUE TITLE
OSX 10.10 Yosemite gem install fails: You have to install development tools first

### ISSUE THREAD

**Issue by PhilCoggins** [cowboyd/therubyracer#304]
Note: this may not be an issue with therubyracer. I have checked https://github.com/cowboyd/therubyracer/issues/301 and this seems to be unrelated to my issue.

I just installed yosemite 10.10, using XCode 6 command line tools (set from XCode).

```
$ gem install therubyracer
Fetching: libv8-3.16.14.3-x86_64-darwin-13.gem (100%)
Successfully installed libv8-3.16.14.3-x86_64-darwin-13
Fetching: therubyracer-0.12.1.gem (100%)
Building native extensions.  This could take a while...
ERROR:  Error installing therubyracer:
    ERROR: Failed to build gem native extension.

    /Users/philcoggins/.rbenv/versions/2.1.2/bin/ruby extconf.rb
checking for main() in -lpthread... *** extconf.rb failed ***
Could not create Makefile due to some reason, probably lack of necessary
libraries and/or headers.  Check the mkmf.log file for more details.  You may
need configuration options.

Provided configuration options:
    --with-opt-dir
    --without-opt-dir
    --with-opt-include
    --without-opt-include=${opt-dir}/include
    --with-opt-lib
    --without-opt-lib=${opt-dir}/lib
    --with-make-prog
    --without-make-prog
    --srcdir=.
    --curdir
    --ruby=/Users/philcoggins/.rbenv/versions/2.1.2/bin/ruby
    --with-pthreadlib
    --without-pthreadlib
/Users/philcoggins/.rbenv/versions/2.1.2/lib/ruby/2.1.0/mkmf.rb:456:in `try_do': The compiler failed to generate an executable file. (RuntimeError)
You have to install development tools first.
    from /Users/philcoggins/.rbenv/versions/2.1.2/lib/ruby/2.1.0/mkmf.rb:541:in `try_link0'
    from /Users/philcoggins/.rbenv/versions/2.1.2/lib/ruby/2.1.0/mkmf.rb:556:in `try_link'
    from /Users/philcoggins/.rbenv/versions/2.1.2/lib/ruby/2.1.0/mkmf.rb:742:in `try_func'
    from /Users/philcoggins/.rbenv/versions/2.1.2/lib/ruby/2.1.0/mkmf.rb:973:in `block in have_library'
    from /Users/philcoggins/.rbenv/versions/2.1.2/lib/ruby/2.1.0/mkmf.rb:918:in `block in checking_for'
    from /Users/philcoggins/.rbenv/versions/2.1.2/lib/ruby/2.1.0/mkmf.rb:351:in `block (2 levels) in postpone'
    from /Users/philcoggins/.rbenv/versions/2.1.2/lib/ruby/2.1.0/mkmf.rb:321:in `open'
    from /Users/philcoggins/.rbenv/versions/2.1.2/lib/ruby/2.1.0/mkmf.rb:351:in `block in postpone'
    from /Users/philcoggins/.rbenv/versions/2.1.2/lib/ruby/2.1.0/mkmf.rb:321:in `open'
    from /Users/philcoggins/.rbenv/versions/2.1.2/lib/ruby/2.1.0/mkmf.rb:347:in `postpone'
    from /Users/philcoggins/.rbenv/versions/2.1.2/lib/ruby/2.1.0/mkmf.rb:917:in `checking_for'
    from /Users/philcoggins/.rbenv/versions/2.1.2/lib/ruby/2.1.0/mkmf.rb:968:in `have_library'
    from extconf.rb:3:in `<main>'

extconf failed, exit code 1

Gem files will remain installed in /Users/philcoggins/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/therubyracer-0.12.1 for inspection.
Results logged to /Users/philcoggins/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/extensions/x86_64-darwin-13/2.1.0-static/therubyracer-0.12.1/gem_make.out
```

```
$ gcc -v
Configured with: --prefix=/Applications/Xcode6-Beta2.app/Contents/Developer/usr --with-gxx-include-dir=/usr/include/c++/4.2.1
Apple LLVM version 6.0 (clang-600.0.34.4) (based on LLVM 3.5svn)
Target: x86_64-apple-darwin14.0.0
Thread model: posix
```

```
$ which gcc
/usr/bin/gcc
```

```
$ xcode-select --install
xcode-select: error: command line tools are already installed, use "Software Update" to install updates
```

Thoughts?

**Comment by JonathanFagan** [comment]
I had the same issue of therubyracer failing. But first, I had libv8 -v '3.16.14.3' failing for me on the first run. I ran gem install libv8 -v '3.16.14.3' -- --with-system-v8 which worked.

Then therubyracer failed. I ran gem install libv8 -v '3.16.14.7' -- --with-system-v8 which worked, then gem install therubyracer and all was well.

**Comment by kevinzzz007** [comment]
Downgrade the Command Line Tools to 6.2 via Apple's Developer Download Page worked for me.
http://stackoverflow.com/questions/29529455/missing-c-header-debug-after-updating-osx-command-line-tools-6-3

**Comment by barhamd** [comment]
+1 for @shanbhardwaj

**Comment by anayib** [comment]
Guys, I fixed it out just running the command  <addr>  xcode-select --install  </addr>    which will be install developers tools. 

Then re-start the terminal/console and run <addr>gem install rails -v 4.2.1 </addr>  or the rails version you want and that's it, it works !, cheers

**Comment by technomage** [comment]
My current gcc has this version:

MBP:skylight-0.6.1 lattam$ gcc -v
Configured with: --prefix=/Applications/Xcode.app/Contents/Developer/usr --with-gxx-include-dir=/usr/include/c++/4.2.1
Apple LLVM version 6.1.0 (clang-602.0.53) (based on LLVM 3.6.0svn)
Target: x86_64-apple-darwin14.3.0
Thread model: posix

**Comment by achempion** [comment]
had the same issue, `gem install libv8 -v '3.16.14.11' -- --with-system-v8` works for me, thank you @JonathanFagan  :)

**Comment by derekhubbard** [comment]
Running `gem install libv8 -v '3.16.14.11' -- --with-system-v8` worked for me as well. Thanks!

**Comment by achempion** [comment]
if someone can't fix this issue, just update ruby version to latest, after update I resolve my problems and libv8 installed by default without any additional options

**Comment by jimbocooper** [comment]
gem install libv8 -v '3.16.14.11' -- --with-system-v8 Worked for me like magic! :) Thanks guys

**Comment by davidwparker** [comment]
I had to upgrade my ruby version for this to work, I was on ruby-2.0.0-p451 and upgraded to ruby-2.0.0-p576 and was fine.

**Comment by gguuss** [comment]
The following steps were necessary for me:

1. Install XCode from app store
1. Install command line tools for XCode - `xcode-select --install`
1. brew install gcc

**Comment by sghiassy** [comment]
@gguuss instructions worked for me. Thx!

**Comment by sohamdas** [comment]
Thanks @gguuss. +1

**Comment by ponyczek** [comment]
Hello,

I had the same as @PhilCoggins 
I have spent 3 hours to fix this.

As it turned out my problem was related to the version of `ruby ` itself.
My mac kept changing the version to `2.0.0...` by default, even though the version specified in `rbenv ` was `2.2.3`

I had to make sure that my 
`ruby -v ` returns  `ruby 2.2.3p173 (2015-08-18 revision 51636) [x86_64-darwin15]`
after that `bundle install`  went smooth as ever.

**Comment by jhgorse** [comment]
@ponyczek I have similar issues. For some reason bundler will not use the rvm'd version of ruby, even when selected. When I manually enter the debugger build directory under the rvm environment it bundles just fine.

The symptom is that it tries to use the system ruby which is immutable and the older 2.0.0. I do not know what causes this.
