### ISSUE TITLE
Bundle fails wil cap deploy

### ISSUE THREAD

**Issue by jfalkson** [cowboyd/therubyracer#305]
Apologies in advance, I am new at this so I hope my description of the issue is enough. Bundle install and gem install work perfectly on my Mac OSX local host, as well as my EC2 Linux instance. However, when I run cap deploy to deploy my rails application the ruby racer gem is not being recognized. 

I am using capistrano 2.15, rails 4, ruby 2.0.0 

Details are here: http://stackoverflow.com/questions/24478212/capistrano-deploy-therubyracer-bundle-error 

Again, if this needs to be moved to a capistrano repo issue page, or if it belongs elsewhere let me know, not sure if this is a bug or just manual error on my part somewhere. I just find it odd that bundle install works except when using the capistrano commands.

**Comment by cowboyd** [comment]
If you can post your Gemfile, Gemfile.lock, we can look into this issue.
