### ISSUE TITLE
How to add window.location support?

### ISSUE THREAD

**Issue by andrewhavens** [cowboyd/therubyracer#321]
I have some JavaScript code that references `window.location.host` to get the current host. This is valid JavaScript when running in a browser, but my RSpec tests are failing because therubyracer and/or V8 does not assume that browser/DOM features are necessary.

Here is a sample of the code I am working with:

```ruby
V8::Context.new.eval 'console.log(window.location.host)'
```

How can I add support for the [`window.location` object](https://developer.mozilla.org/en-US/docs/Web/API/Window.location)?

**Comment by cowboyd** [comment]
you need to embed an object named `window` into your context. Please see the README for details.
