### ISSUE TITLE
therubyracer gem installation fail - Makefile missing separator

### ISSUE THREAD

**Issue by NamNguyen52** [cowboyd/therubyracer#335]
Gem::Ext::BuildError: ERROR: Failed to build gem native extension.

    /Users/NamNguyen/.rvm/rubies/ruby-2.1.5/bin/ruby -r ./siteconf20150325-50446-1tyslqz.rb extconf.rb --with-system-v8
checking for main() in -lpthread... yes
checking for main() in -lobjc... yes
creating Makefile

make "DESTDIR=" clean
Makefile:83: *** missing separator.  Stop.

make "DESTDIR="
Makefile:83: *** missing separator.  Stop.

make failed, exit code 2

Gem files will remain installed in /Users/NamNguyen/.rvm/gems/ruby-2.1.5@rev1
rev1/gems/therubyracer-0.12.1 for inspection.
Results logged to /Users/NamNguyen/.rvm/gems/ruby-2.1.5@rev1
rev1/extensions/x86_64-darwin-14/2.1.0-static/therubyracer-0.12.1/gem_make.out
An error occurred while installing therubyracer (0.12.1), and Bundler cannot continue.
Make sure that `gem install therubyracer -v '0.12.1'` succeeds before bundling.

I've tried fixing this with the following post with no luck:
- http://stackoverflow.com/questions/19630154/gem-install-therubyracer-v-0-10-2-on-osx-mavericks-not-installing/20145328#20145328

**Comment by ignisf** [comment]
@NamNguyen52 what was the issue?
