### ISSUE TITLE
Can't load JS file from JS code

### ISSUE THREAD

**Issue by dreamiurg** [cowboyd/therubyracer#383]
I can't figure out how to load JS code from a separate file from within JS code running in this Ruby wrapper.

Example code:
```ruby
require 'v8'

ctx = V8::Context.new
ctx.eval('load("file.js");')
```

Error message:
```
% ruby test.rb
at <eval>:1:1: load is not defined (V8::Error)
	from test.rb:4:in `<main>'

% ruby --version
ruby 1.9.3p551 (2014-11-13 revision 48407) [x86_64-darwin14.4.0]
```

**Comment by dreamiurg** [comment]
Alright, I figured out that load() is present only for v8 shell.cc 

https://code.google.com/p/v8/source/browse/trunk/samples/shell.cc

**Comment by cowboyd** [comment]
That is correct. By default, the JavaScript environment is pristine. No function that is not in the JS spec is available. Note that you could implement `load()` in Ruby though:

```ruby
ctx = V8::Context.new
