### ISSUE TITLE
Support latest 4.5 libv8 ?

### ISSUE THREAD

**Issue by bjm88** [cowboyd/therubyracer#388]
When I install by default libv8 it installs..
Successfully installed libv8-4.5.95.5-x86_64-darwin-14
Mac OS X 10.10 yosmite

However our new developers have issues trying do bundle install with the rubyracer in GemFile.  We dont declare any special version of anything in our GemFile.   Does rubyracer plan to support latest libv8 package?

**Comment by ignisf** [comment]
https://github.com/cowboyd/therubyracer/pull/348

**Comment by cowboyd** [comment]
We don't have a schedule for when this will be released, but it is being actively worked on. There are some pretty major bugs to fix, combined with some massive API changes on the part of V8. If I had to guess, I'd say it would be late 2015, early 2016

**Comment by bjm88** [comment]
Ok thank you for the update.  We will be keeping an eye.
-Ben

Benjamin Maisano
CTO
Ben@CareDox.com
1.973.531.7048
