### ISSUE TITLE
Symbol not found when running Rails server

### ISSUE THREAD

**Issue by jasonlynes** [cowboyd/therubyracer#392]
Having trouble finding answers elsewhere... 

OSX El Capitan 10.11.1
Ruby 2.2.2 (Rbenv)
Rails 4.2.4

I successfully installed therubyracer 0.12.2 and libv8 3.16.14.13, and successfully ran `bundle install`, but when i run `puma` or `rails s` I get the following error:

```
dyld: lazy symbol binding failed: Symbol not found: __ZN2v82V821AddGCPrologueCallbackEPFvNS_6GCTypeENS_15GCCallbackFlagsEES1_
  Referenced from: /Users/jason/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/extensions/x86_64-darwin-15/2.2.0-static/therubyracer-0.12.2/v8/init.bundle
  Expected in: flat namespace

dyld: Symbol not found: __ZN2v82V821AddGCPrologueCallbackEPFvNS_6GCTypeENS_15GCCallbackFlagsEES1_
  Referenced from: /Users/jason/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/extensions/x86_64-darwin-15/2.2.0-static/therubyracer-0.12.2/v8/init.bundle
  Expected in: flat namespace

Trace/BPT trap: 5
```

**Comment by jasonlynes** [comment]
Switched to Ruby 2.0.0, everything else the same. Reinstalled the gems and no such server errors.

**Comment by cowboyd** [comment]
Did you uninstall all copies of libv8 and also remove all sticky --with-system-v8 flags, and remove any brew installed v8 for good measure?  .

**Comment by phuongnd08** [comment]
Without brew installed v8 I won't be able to install `therubyracer` on Mac.

**Comment by shakycode** [comment]
Anyone get a resolution to this?  I'm having the same issues with Rails 4.2.1 and Ruby 2.2.2.

**Comment by Zhyliana** [comment]
+1

Same issues with Rails 3.2.22 and Ruby 2.1.6p336 also on El Capitan

**Comment by BeeZerk** [comment]
same problem on el capitan

**Comment by cleytonmessias** [comment]
+1

**Comment by sergeygaychuk** [comment]
same problem on el capitan

**Comment by saurabhnanda** [comment]
Same problem. Tried the solution given at http://stackoverflow.com/questions/33475709/install-therubyracer-gem-on-osx-10-11-el-capitan but still getting the following error:

```
	/Users/saurabhnanda/.rvm/gems/ruby-2.2.1@vl/gems/activesupport-3.2.21/lib/active_support/values/time_zone.rb:270: warning: circular argument reference - now
dyld: lazy symbol binding failed: Symbol not found: __ZN2v82V821AddGCPrologueCallbackEPFvNS_6GCTypeENS_15GCCallbackFlagsEES1_
  Referenced from: /Users/saurabhnanda/.rvm/gems/ruby-2.2.1@vl/gems/therubyracer-0.12.0/lib/v8/init.bundle
  Expected in: flat namespace

dyld: Symbol not found: __ZN2v82V821AddGCPrologueCallbackEPFvNS_6GCTypeENS_15GCCallbackFlagsEES1_
  Referenced from: /Users/saurabhnanda/.rvm/gems/ruby-2.2.1@vl/gems/therubyracer-0.12.0/lib/v8/init.bundle
  Expected in: flat namespace
```

**Comment by chip-miller** [comment]
+1

**Comment by wendelu1991** [comment]
+1 and when I switched back to 2.0.0, same errors still appeared.

**Comment by P1X3L** [comment]
+1 exact same problem

**Comment by nishants** [comment]
Same problem here too(ruby 2.1.4p265 ; ElCapiton)

**Comment by sun-yr** [comment]
same problem
ruby: 2.3.0p0 (2015-12-25 revision 53290) [x86_64-darwin15]
os: El Capitan

**Comment by zoontek** [comment]
This works for me:

```
gem uninstall libv8
gem uninstall therubyracer
brew rm v8 (or v8-315)

brew tap homebrew/dupes
brew install apple-gcc42
bundle config --local build.libv8 --with-cxx=/usr/local/bin/g++-4.2
bundle install
```

**Comment by ldrbrandon** [comment]
I'm still experiencing this issue. libv8 won't install successfully. 
I'm on mac os 10.11.4, ruby 1.9.3-p551 
I did the above sequence but bundle install failed and logged this:
```
1 error generated.
make[1]: *** [/Users/bdog/.rvm/gems/ruby-1.9.3-p551/gems/libv8-3.16.14.7/vendor/v8/out/x64.release/obj.target/preparser_lib/src/conversions.o] Error 1
make: *** [x64.release] Error 2
/Users/bdog/.rvm/gems/ruby-1.9.3-p551/gems/libv8-3.16.14.7/ext/libv8/location.rb:36:in `block in verify_installation!': libv8 did not install properly, expected binary v8 archive
```

**Comment by ignisf** [comment]
There has been a new release of libv8 that should address most OS X install issues. Closing for now.

**Comment by rbudiharso** [comment]
This happens to me
```
dyld: lazy symbol binding failed: Symbol not found: __ZN2v82V821AddGCPrologueCallbackEPFvNS_6GCTypeENS_15GCCallbackFlagsEES1_
  Referenced from: /Users/rbudiharso/.asdf/installs/ruby/2.2.10/lib/ruby/gems/2.2.0/extensions/x86_64-darwin-18/2.2.0-static/therubyracer-0.12.1/v8/init.bundle
  Expected in: flat namespace

dyld: Symbol not found: __ZN2v82V821AddGCPrologueCallbackEPFvNS_6GCTypeENS_15GCCallbackFlagsEES1_
  Referenced from: /Users/rbudiharso/.asdf/installs/ruby/2.2.10/lib/ruby/gems/2.2.0/extensions/x86_64-darwin-18/2.2.0-static/therubyracer-0.12.1/v8/init.bundle
  Expected in: flat namespace

[1]    97505 abort      bundle exec rails s
```
Mac OS Mojave, ruby 2.2.10

**Comment by bstawitz** [comment]
Same problem.

Mac OS Mojave ruby 2.3.5

**Comment by gbenedict** [comment]
I just ran into this problem on macOS Catalina. I could not install with 0.12.2, but I could with 0.12.3.

1. brew install v8-315
2. gem install libv8 -v='3.16.14.19' -- --with-system-v8
3. gem install therubyracer -v '0.12.3' -- --with-v8-dir=/usr/local/opt/v8@3.15
4. bundle update therubyracer

This was with an older Rails 4.0.8 application running Spree.

**Comment by wheresmyconcrete** [comment]
Thank you gbenedict. It worked for me.

**Comment by electricfeel1979** [comment]
I am having this issue on Mac m1, it was already a painful to install therubyracer and to successfully bundle install, and in the end I am facing this issue.

> dyld: lazy symbol binding failed: Symbol not found: __ZN2v82V821AddGCPrologueCallbackEPFvNS_6GCTypeENS_15GCCallbackFlagsEES1_
>   Referenced from: /Users/kevin/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/therubyracer-0.12.3/lib/v8/init.bundle
>   Expected in: flat namespace
> 
> dyld: Symbol not found: __ZN2v82V821AddGCPrologueCallbackEPFvNS_6GCTypeENS_15GCCallbackFlagsEES1_
>   Referenced from: /Users/kevin/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/therubyracer-0.12.3/lib/v8/init.bundle
>   Expected in: flat namespace

> zsh: abort      rails s

**Comment by cheesepaulo** [comment]
> I am having this issue on Mac m1, it was already a painful to install therubyracer and to successfully bundle install, and in the end I am facing this issue.
> 
> ```
> dyld: lazy symbol binding failed: Symbol not found: __ZN2v82V821AddGCPrologueCallbackEPFvNS_6GCTypeENS_15GCCallbackFlagsEES1_
>   Referenced from: /Users/kevin/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/therubyracer-0.12.3/lib/v8/init.bundle
>   Expected in: flat namespace
> 
> dyld: Symbol not found: __ZN2v82V821AddGCPrologueCallbackEPFvNS_6GCTypeENS_15GCCallbackFlagsEES1_
>   Referenced from: /Users/kevin/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/therubyracer-0.12.3/lib/v8/init.bundle
>   Expected in: flat namespace
> 
> zsh: abort      rails s
> ```

same here, m1 Big Sur 11.2.1 ( rbenv native ruby 2.6.4 )

**Comment by taco-chen** [comment]
Same here at M1 Big Sur 11.3 (ruby 2.7.3)

```
dyld: lazy symbol binding failed: Symbol not found: __ZN2v82V821AddGCPrologueCallbackEPFvNS_6GCTypeENS_15GCCallbackFlagsEES1_
  Referenced from: /Users/weifanchen/.asdf/installs/ruby/2.7.3/lib/ruby/gems/2.7.0/gems/therubyracer-0.12.3/lib/v8/init.bundle
  Expected in: flat namespace

dyld: Symbol not found: __ZN2v82V821AddGCPrologueCallbackEPFvNS_6GCTypeENS_15GCCallbackFlagsEES1_
  Referenced from: /Users/weifanchen/.asdf/installs/ruby/2.7.3/lib/ruby/gems/2.7.0/gems/therubyracer-0.12.3/lib/v8/init.bundle
  Expected in: flat namespace

[1]    67201 abort      bundle exec rails c
```

**Comment by markcelsor** [comment]
> Same here at M1 Big Sur 11.3 (ruby 2.7.3)
> 
> ```
> dyld: lazy symbol binding failed: Symbol not found: __ZN2v82V821AddGCPrologueCallbackEPFvNS_6GCTypeENS_15GCCallbackFlagsEES1_
>   Referenced from: /Users/weifanchen/.asdf/installs/ruby/2.7.3/lib/ruby/gems/2.7.0/gems/therubyracer-0.12.3/lib/v8/init.bundle
>   Expected in: flat namespace
> 
> dyld: Symbol not found: __ZN2v82V821AddGCPrologueCallbackEPFvNS_6GCTypeENS_15GCCallbackFlagsEES1_
>   Referenced from: /Users/weifanchen/.asdf/installs/ruby/2.7.3/lib/ruby/gems/2.7.0/gems/therubyracer-0.12.3/lib/v8/init.bundle
>   Expected in: flat namespace
> 
> [1]    67201 abort      bundle exec rails c
> ```

I was finally able to get past this on my M1 Big Sur 11.4 (ruby 2.7.2) by installing brew, v8, libv8, and therubyracer individually using `arch -x86_64`. Initially I wasn't installing the gems with it and it was causing the error above.

```
arch -x86_64 /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install.sh)"
alias ibrew='arch -x86_64 /usr/local/bin/brew'
ibrew install v8@3.15
arch -x86_64 gem install libv8 -v '3.16.14.19' -- --with-system-v8 
arch -x86_64 gem install therubyracer -v '0.12.3' -- --with-v8-dir=/usr/local/opt/v8@3.15
```

**Comment by pinkyrout** [comment]
Mac OS Big Sur Issue solve for mini-racer gem:
I faced similar error with mini_racer gem. I updated the version from 3.0.1 to 4.0.0 in my gemfile and it worked. Not getting any error now. Mostly it is the problem of version. Sometimes the version of the gem is not compatible with our OS version and this problem can occur. I was using macOS Big Sur. Many old versions of gems are not compatible with it.

**Comment by atticusliu** [comment]
I've been following along with a new M1 machine and having the usual troubles above. After following @markcelsor's instructions and executing basic rails commands, I'm seeing errors along the lines of:

> .../lib/v8/init.bundle, 9) no suitable image found.
>  Did find: (LoadError)
 > .../gems/therubyracer-0.12.3/lib/v8/init.bundle: mach-o, but wrong architecture
> .../gems/therubyracer-0.12.3/lib/v8/init.bundle: mach-o, but wrong architecture -
> .../gems/therubyracer-0.12.3/lib/v8/init.bundle

Can't seem to find any other resource that covers therubyracer and wrong architecture issues. Using macOS Big Sur.

**Comment by wbharding** [comment]
After a couple hours research on this, I moved to `mini_racer`, which allowed me to get Rails started and doesn't need the alternate version of the `v8` gem. Given that therubyracer hasn't been maintained in several years, this might be a good time for others to consider the switch. I'll post again if I run into any issues in our app from the change.
