### ISSUE TITLE
V8 causing weak references in session objects

### ISSUE THREAD

**Issue by hlascelles** [cowboyd/therubyracer#397]
We were recently running into issues where our session `inspect` calls were crashing with a **WeakRef::RefError: Invalid Reference - probably recycled**. (Specifically, it was being triggered by Devise https://github.com/plataformatec/devise/issues/3828).

A report of the class hierarchy yielded this:

```
self.class.ancestors = [ActionDispatch::Request::Session, Object, PP::ObjectMixin, V8::Conversion::Object, JSON::Ext::Generator::GeneratorMethods::Object, Kernel, BasicObject]
```

And sure enough the `V8::Conversion::Object` interloper was causing session objects to be unsafely garbage collected.

The only fix we found was to remove therubyracer altogether from deployed environments.

**Comment by cowboyd** [comment]
Without an explanation of why, it's unclear if this is an issue with therubyracer. My guess is that there is simply a method naming conflict between therubyracer and devise, but without a diagnosis it's impossible to tell.
