### ISSUE TITLE
How to load jQuery source code

### ISSUE THREAD

**Issue by Simcookies** [cowboyd/therubyracer#401]
I want to write test foe some js function, but it need jquery, so If can I load jquery sorce code directly? Like this:
`cxt.load("XXXX/jquery.min.js")` 
It seems errors come out: 
`V8::Error: Cannot call method 'createElement' of undefined`

**Comment by cowboyd** [comment]
The Ruby Racer does not provide a browser environment or a DOM API, those are the responsibility of the embedder. It is just javascript.
