### ISSUE TITLE
Compilation error

### ISSUE THREAD

**Issue by Hax4us** [cowboyd/therubyracer#445]
i executed this command 
gem install therubyracer -v 0.12.2
So here is mkmf.log details

"aarch64-linux-android-clang -o conftest -I/data/data/com.termux/files/usr/include/ruby-2.4.0/aarch64-linux-android -I/data/data/com.termux/files/usr/include/ruby-2.4.0/ruby/backward -I/data/data/com.termux/files/usr/include/ruby-2.4.0 -I. -I/data/data/com.termux/files/usr/include -isystem /data/data/com.termux/files/usr/include/libandroid-support    -Oz -fPIC conftest.c  -L. -L/data/data/com.termux/files/usr/lib -L. -L/data/data/com.termux/files/usr/lib -landroid-support -fstack-protector -rdynamic -Wl,-export-dynamic     -lruby  -lgmp -ldl -lm   -lc"
cc1: error: argument to '-O' should be a non-negative integer, 'g', 's' or 'fast'
checked program was:
/* begin */
1: #include "ruby.h"
2: 
3: int main(int argc, char **argv)
4: {
5:   return 0;
6: }
/* end */

thnx for your really hard work :)

**Comment by ignisf** [comment]
Hey, I see your issue now, let's continue here: https://github.com/cowboyd/libv8/issues/257
