### ISSUE TITLE
(Lion) Runtime crash lazy symbol binding failed: Symbol not found: __ZN2v86LockerC1Ev 

### ISSUE THREAD

**Issue by JamesKyburz** [cowboyd/therubyracer#94]
I am getting the following error on Lion any ideas?
V8 and therubyracer where installed with no errors.

V8 version 3.5.4.3
therubyracer (0.9.3, 0.9.2)

ruby-1.9.2-p0 :001 > require 'v8'
dyld: lazy symbol binding failed: Symbol not found: __ZN2v86LockerC1Ev
  Referenced from: /Users/jameskyburz/.rvm/gems/ruby-1.9.2-p0@rich_webapp/gems/therubyracer-0.9.3/ext/v8/v8.bundle
  Expected in: flat namespace

dyld: Symbol not found: __ZN2v86LockerC1Ev
  Referenced from: /Users/jameskyburz/.rvm/gems/ruby-1.9.2-p0@rich_webapp/gems/therubyracer-0.9.3/ext/v8/v8.bundle
  Expected in: flat namespace

zsh: trace trap  irb

**Comment by gl0wa** [comment]
Had same issue and fixed it with:
```brew uninstall v8```
```gem uninstall therubyracer```
```gem install therubyracer```
